### ISSUE TITLE
dracut: ignition-files and ostree ordering

### ISSUE THREAD

**Issue by lucab** [dustymabe/ignition-dracut#20]
Context: #17 prepares for ignition-disks in initramfs. In its initial version I was trying to run it right before ignition-files, and @dustymabe caught a few issue with that. In retrospect ignition-disks should run much earlier. This is a similarly concerned followup for ignition-files too.

Here we are now ordering ignition-files after `initrd-switch-root.target`, while on CL it was running before `initrd-parse-etc.service`. Cross-checking with https://www.freedesktop.org/software/systemd/man/bootup.html, you can see that there is a `initrd-cleanup.service` in-between, which isolates to a specific target.

Current setup seems to work, however I have the following concerns:
 * by running that late, we can't anymore drop files for `initrd-parse-etc` (e.g. initrd mount units)
 * running after isolate means that most initramfs services are down. Network and udev are the most interesting ones for us
 * I had to cut dependency links between disks and files stage

I think ignition-files has been moved that late because of ostree, but I think we should consider moving it back where it was originally, if possible.

**Comment by ajeddeloh** [comment]
Does ostree need to run so late?

**Comment by cgwalters** [comment]
> Does ostree need to run so late?

Offhand I am not sure of a reason we couldn't do:

```
diff --git a/src/boot/ostree-prepare-root.service b/src/boot/ostree-prepare-root.service
index 52cf8863..1ec985cb 100644
--- a/src/boot/ostree-prepare-root.service
+++ b/src/boot/ostree-prepare-root.service
@@ -21,8 +21,8 @@ DefaultDependencies=no
 ConditionKernelCommandLine=ostree
 ConditionPathExists=/etc/initrd-release
 OnFailure=emergency.target
-After=initrd-switch-root.target
-Before=initrd-switch-root.service
+After=initrd-root-fs.target
+Before=initrd-parse-etc.service
 Before=plymouth-switch-root.service
 
 [Service]
```

(But not tested, only thought about it briefly etc.)

**Comment by jlebon** [comment]
> (But not tested, only thought about it briefly etc.)

Yup, I can confirm that does Just Work in FCOS. I think it's worth trying to get this upstream in ostree proper once I verify it doesn't somehow negatively affect FAH and RHCOS either.
