### ISSUE TITLE
qemu_fw_cfg not included in initrd

### ISSUE THREAD

**Issue by thkukuk** [dustymabe/ignition-dracut#22]
If run under qemu, ignition does a modprobe qemu_fw_cfg. But the module will never be placed into the initrd with the current scripts.

**Comment by jlebon** [comment]
Hmm, it's definitely here in the a local build of [FCOS](https://github.com/coreos/fedora-coreos-config) here:

```
lsinitrd /boot/ostree/coreos-6e5b0a3f88451cfac85097ac118414c1e9fc5037e1a0ef559dcb21c4a73bb1ff/initramfs-4.18.5-300.fc29.x86_64.img
...
-rw-r--r--   1 root     root         5960 Jan  1  1970 usr/lib/modules/4.18.5-300.fc29.x86_64/kernel/drivers/firmware/qemu_fw_cfg.ko.xz
...
```

Without it, we wouldn't be able to boot up the image at all.
In what context did you encounter this?

If this is about making that dep explicit, then... yeah I think that makes sense.

**Comment by dustymabe** [comment]
I think he is trying to use ignition without Fedora (i.e. he might have a different initramfs setup than what we have in Fedora so we might need to be more explicit about our requirements.

**Comment by thkukuk** [comment]
Correct, sorry, I forgot to mention: I'm using openSUSE Tumbleweed for the tests.

**Comment by Conan-Kudo** [comment]
Are we using the generic initramfs configuration in Fedora CoreOS? That might be the difference here...

**Comment by jlebon** [comment]
https://github.com/dustymabe/ignition-dracut/pull/25
